[env]
TERM = "xterm-256color"

[font]
size = 10.0
offset = { x = 0, y = 1 }
glyph_offset = { x = 0, y = 1}

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[window]
padding = { x = 6, y = 10 }
dynamic_padding = false
opacity = 1.0

[scrolling]
history=5000
